name: Deploy Python Flask Application on Azure App Service Web App

env:
  AZURE_WEBAPP_NAME: unifinder-data  # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: microservices/data

on:
  push:
    branches: [ "main", "data", "fixer" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Apply venv and zip the content
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          zip release.zip ./* -r

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_WEB_APP_UNIFINDER_DATA_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/release.zip
          
  
