
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Python Flask Application on Azure App Service Web App

on:
  push:
    branches: ['main', 'fixer']
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: unifinder-data  # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: microservices/data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      - name: Zip artifact for deployment
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/release.zip
            !${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_WEB_APP_UNIFINDER_DATA_PUBLISH_PROFILE }}
          